### ISSUE TITLE
Some feedback on reproducibility in Ubuntu

### ISSUE THREAD

**Issue by dimachine** [rvyjidacek/experiments-cla2020#1]
#Latest Python 3 is installed. Latest Swift for Ubuntu is installed. Ubuntu 22.04.3 LTS

/experiments-cla2020# sh run.sh datasets
Running time benchmark
Fetching https://github.com/rvyjidacek/FcaKit.git
Fetched https://github.com/rvyjidacek/FcaKit.git (2.89s)
Computing version for https://github.com/rvyjidacek/FcaKit.git
Computed https://github.com/rvyjidacek/FcaKit.git at 1.2.1 (0.36s)
Computed https://github.com/rvyjidacek/FcaKit.git at 1.2.1 (0.00s)
Creating working copy for https://github.com/rvyjidacek/FcaKit.git
Working copy of https://github.com/rvyjidacek/FcaKit.git resolved at 1.2.1
Building for production...
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^
error: fatalError

Compare coverage of GreCon and GreConD
Building for production...
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^
error: fatalError

Building for production...
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^
error: fatalError

Generating graphs
/usr/bin/env: 'python': No such file or directory
Coverage graphs of GreCon and GreConD
Building for production...
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^
error: fatalError

Building for production...
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^
error: fatalError

/usr/bin/env: 'python': No such file or directory
Coverage graphs of GreCon2 and GreConD
Building for production...
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^
error: fatalError

Building for production...
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^
error: fatalError

/usr/bin/env: 'python': No such file or directory
Coverage graphs of GreCon2 on A(I) and O(I) and GreConD
Building for production...
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^
error: fatalError

Building for production...
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^
error: fatalError

/usr/bin/env: 'python': No such file or directory

**Comment by dimachine** [comment]
Almost the same on Mac.
(base) MacBook-Pro-Dmitrij:experiments-cla2020 dmitry$ sh run.sh datasets
Running time benchmark
Fetching https://github.com/rvyjidacek/FcaKit.git
[769/769] Fetching objects
Fetched https://github.com/rvyjidacek/FcaKit.git (2.43s)
Computing version for https://github.com/rvyjidacek/FcaKit.git
Computed https://github.com/rvyjidacek/FcaKit.git at 1.2.1 (0.87s)
Computed https://github.com/rvyjidacek/FcaKit.git at 1.2.1 (0.00s)
Creating working copy for https://github.com/rvyjidacek/FcaKit.git
Working copy of https://github.com/rvyjidacek/FcaKit.git resolved at 1.2.1
Building for production...
/Users/dmitry/experiments-cla2020/.build/checkouts/FcaKit/Sources/FcaKit/BMF/Matrix.swift:37:17: warning: variable 'columns' was never mutated; consider changing to 'let' constant
            var columns = row.enumerated()
            ~~~ ^
            let
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^

Compare coverage of GreCon and GreConD
Building for production...
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^

Building for production...
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^

Generating graphs
Traceback (most recent call last):
  File "./generate-graph.py", line 44, in <module>
    generate_graph(0.5, 90000, '{}firewall1-coverage.csv'.format(folder), 'results/graphs/grecon-vs-grecond/firewall1.eps')
  File "./generate-graph.py", line 14, in generate_graph
    with open(input_file, 'r') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/Grecon-vs-Grecond/firewall1-coverage.csv'
Coverage graphs of GreCon and GreConD
Building for production...
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^

Building for production...
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^

Traceback (most recent call last):
  File "./coverage-graph.py", line 63, in <module>
    generate_graph(2,1500,8,['s', 'x'],("GreCon", "GreConD"),'{}{}'.format(sys.argv[2], 'firewall1-coverage.csv'), '{}{}'.format(sys.argv[3], 'firewall1.eps'))
  File "./coverage-graph.py", line 13, in generate_graph
    with open(input_file, 'r') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/Grecon-vs-Grecond-Coverage/firewall1-coverage.csv'
Coverage graphs of GreCon2 and GreConD
Building for production...
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^

Building for production...
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^

Traceback (most recent call last):
  File "./coverage-graph.py", line 72, in <module>
    generate_graph(2,1500,8,['>', 'x'],("GreCon2", "GreConD"),'{}{}'.format(sys.argv[2], 'firewall1-coverage.csv'), '{}{}'.format(sys.argv[3], 'firewall1.eps'))
  File "./coverage-graph.py", line 13, in generate_graph
    with open(input_file, 'r') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/Grecon2-vs-Grecond-Coverage/firewall1-coverage.csv'
Coverage graphs of GreCon2 on A(I) and O(I) and GreConD
Building for production...
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^

Building for production...
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:116:15: error: expected initial value after '='
    let path = 
              ^
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:115:13: error: function cannot be declared public because its parameter uses an internal type
public func loadFactorisation(algorithm: Algorithm, dataset: String) {
            ^                            ~~~~~~~~~
/Users/dmitry/experiments-cla2020/Sources/experiments-cla2020/Utilities/Benchmarks.swift:110:6: note: type declared here
enum Algorithm {
     ^

Traceback (most recent call last):
  File "./coverage-graph.py", line 72, in <module>
    generate_graph(2,1500,8,['>', 'x'],("GreCon2", "GreConD"),'{}{}'.format(sys.argv[2], 'firewall1-coverage.csv'), '{}{}'.format(sys.argv[3], 'firewall1.eps'))
  File "./coverage-graph.py", line 13, in generate_graph
    with open(input_file, 'r') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/restricted-grecon2-factorization/firewall1-coverage.csv'

**Comment by rvyjidacek** [comment]
Thank you. I will look at it.
